#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'gntp==1.0.2','console_scripts','gntp'
__requires__ = 'gntp==1.0.2'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('gntp==1.0.2', 'console_scripts', 'gntp')()
)
